- name: Check Config
  win_shell: |
    $config = @{}
    foreach ($path in $env:Path) { if ($path -like "*git*") {$config.Add("Git", $True)}else {$config.Add("Git", $False)} }
    $config.Add("Hyperv", (Get-WindowsFeature -Name "Hyper-v").installed)
    $config.Add("Dhcp", (Get-WindowsFeature -Name "DHCP").installed)
    foreach ($switch in Get-VMSwitch) { if ($switch.Name -eq "NATSwitch") {$config.Add("Switch", $True)}else {$config.Add("Switch", $False)} }
    $config | ConvertTo-Json
  register: config
- name: fact
  set_fact:
    config: "{{ config.stdout | from_json }}"
- name: Download git-client
  win_get_url:
    url: https://github.com/git-for-windows/git/releases/download/v2.20.1.windows.1/Git-2.20.1-64-bit.exe
    dest: C:\Windows\Temp
  when: config.Git == False
- name: install git-client
  raw: 'C:\Windows\Temp\Git-2.20.1-64-bit.exe /SILENT /COMPONENTS="icons,ext\reg\shellhere,assoc,assoc_sh"'
  when: config.Git == False
- name: Set Winrm to trust all hosts
  win_shell: winrm s winrm/config/client '@{TrustedHosts="*"}'
- name: Clone Git Repo
  win_shell: git clone {{GitRepo}} {{GitRepoPath}}
